export interface NewsArticle {
  title: string
  summary: string
  date: string
  source: string
  url: string
  image?: string
}

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    title: 'Too Lost Partners with Roblox to Bring Catalog of Independent Music to Games and Virtual Spaces',
    summary: 'Deal adds thousands of Too Lost-distributed tracks — including music by The All-American Rejects, A$AP Ferg, Teddy Swims, and Alex Warren — to the Roblox Creator Store for use across games and virtual spaces.',
    date: '2026-07-28',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/too-lost-partners-with-roblox-to-bring-catalog-of-independent-music-to-games-and-virtual-spaces/',
    image: 'https://www.musicbusinessworldwide.com/files/2026/07/Too-Lost-x-Roblox.jpg',
  },
  {
    title: 'Too Lost Acquires Australia\'s GYRO.Group in First Acquisition Since Nine-Figure Raise',
    summary: 'Too Lost acquires Brisbane-based GYRO.Group, extending its footprint across Australia, New Zealand, and the wider Asia-Pacific region. G.Y.R.O. co-founder Andy Irvine becomes Head of APAC at Too Lost.',
    date: '2026-07-15',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/too-lost-acquires-australias-gyro-group-in-first-acquisition-since-nine-figure-raise/',
    image: 'https://www.musicbusinessworldwide.com/files/2026/07/Screenshot-2026-07-15-at-11.46.29-e1784112425622.jpg',
  },
  {
    title: 'Jay Moore Appointed Chief Investment Officer at Too Lost',
    summary: 'Moore joins from Position Music to lead investment strategy as Too Lost expands its catalog and capital platform.',
    date: '2026-05-28',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/jay-moore-appointed-chief-investment-officer-at-too-lost/',
    image: 'https://www.musicbusinessworldwide.com/files/2026/05/Screenshot-2026-05-28-at-15.00.33.jpg',
  },
  {
    title: 'Too Lost Raises Capital From TA Associates and GoldState',
    summary: 'Distribution and artist services platform secures strategic investment led by GoldState Music and TA Associates to fuel global expansion.',
    date: '2026-03-16',
    source: 'Billboard',
    url: 'https://www.billboard.com/pro/too-lost-raises-investment-ta-associates-goldstate/',
    image: 'https://www.billboard.com/wp-content/uploads/2026/02/P11DWTP-e1770740562598.jpg?w=1024',
  },
  {
    title: 'Too Lost Launches Profile Defender to Shield Artists From AI-Driven Fakes',
    summary: 'New feature monitors and prevents unauthorized AI-generated content from appearing on artists\' streaming profiles.',
    date: '2026-03-02',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2026/03/02/too-lost-profile-defender-feature/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2026/03/too-lost-profile-defender.png',
  },
  {
    title: 'Too Lost Saw 130% Growth Over 2025—Here\'s What\'s Next',
    summary: 'CEO Gregory Hirschhorn reflects on major milestones including revenue growth, new ventures, and plans for 2026.',
    date: '2026-01-22',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2026/01/22/too-lost-2025-milestone-growth/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2026/01/too-lost-greg-hirschhorn-statement-2026.jpeg',
  },
  {
    title: 'Too Lost Partners with Xposure Music to Co-Fund Catalog Acquisitions',
    summary: 'Partnership plans to deploy tens of millions of dollars in upcoming catalog deals, combining data-driven valuation with global distribution infrastructure.',
    date: '2025-10-30',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/too-lost-partners-with-xposure-music-to-co-fund-catalog-acquisitions-with-plans-to-deploy-tens-of-millions-of-dollars-in-upcoming-deals/',
    image: 'https://www.musicbusinessworldwide.com/files/2025/10/Screenshot-2025-10-30-at-3.19.09-PM-e1761808973797.jpg',
  },
  {
    title: 'The All-American Rejects Sign Global Distribution Deal with Too Lost',
    summary: 'Pop-rock band debuts under independent banner with first album in over a decade, distributed globally through Too Lost.',
    date: '2025-10-21',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/10/21/the-all-american-rejects-too-lost-distribution/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/10/the-all-american-rejects-too-lost.jpeg.jpg',
  },
  {
    title: 'Too Lost Makes Seven-Figure Investment in Rebellion Records',
    summary: 'Investment accelerates viral marketing-driven indie label that generated over 5 billion streams since its 2023 launch.',
    date: '2025-10-09',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/too-lost-makes-seven-figure-investment-into-independent-label-rebellion-records/',
    image: 'https://www.musicbusinessworldwide.com/files/2025/10/two-dudes-16x9_BW.jpg',
  },
  {
    title: 'Too Lost Makes Seven-Figure Investment in AntiFragile Equity Partners',
    summary: 'Investment supports catalog acquisition startup focused on acquiring and monetizing undervalued music rights.',
    date: '2025-10-15',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/too-lost-makes-seven-figure-investment-in-catalog-acquisition-startup-antifragile-equity-partners/',
    image: 'https://www.musicbusinessworldwide.com/files/2025/10/Screenshot-2025-10-15-at-11.51.22-e1760525547278.jpg',
  },
  {
    title: 'EVEN Partners with Too Lost to Bring Direct-to-Fan Sales to 400,000 Artists',
    summary: 'Integration gives artists access to D2C storefronts and daily payouts, proving superfans can outperform hundreds of thousands of passive listeners.',
    date: '2025-09-24',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/even-partners-with-too-lost-to-bring-direct-to-fan-sales-to-400000-artists-and-labels/',
    image: 'https://www.musicbusinessworldwide.com/files/2025/07/Mag-Rodriguez_new.jpg',
  },
  {
    title: 'On the Radar UK Series Launched with Olympus Projects & Too Lost',
    summary: 'Expansion into UK market spotlights London\'s underground music scene across drill, grime, rap, and experimental genres.',
    date: '2025-09-10',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/09/10/on-the-radar-uk-series/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/09/on-the-radar-uk-feat.jpg',
  },
  {
    title: 'Too Lost Achieves #90 on Inc. 5000, #2 in Media & Entertainment',
    summary: 'Named among America\'s fastest-growing private companies with top honors in media sector and NYC rankings.',
    date: '2025-08-28',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/08/28/too-lost-inc-5000-inclusion/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/08/too-lost-inc-5000.png',
  },
  {
    title: 'Too Lost Expands to Brazil with Olympus Projects',
    summary: 'Partnership launches On the Radar Brazil, generating hundreds of millions of views and multiple Spotify Viral 100 entries.',
    date: '2025-06-02',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/06/02/too-lost-olympus-projects-brazil-music/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/06/too-lost-olympus-projects-brazil.png',
  },
  {
    title: 'Too Lost World Building Panel at Dream Con',
    summary: 'Company shares insights on building the future of independent music infrastructure at major industry conference.',
    date: '2025-05-27',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/05/27/too-lost-world-building-panel-dream-con/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/05/too-lost-presents-dream-con-panel.png',
  },
  {
    title: 'Too Lost Unveils Mobile Platform for Anywhere, Anytime Access',
    summary: 'New iOS and Android app gives artists complete distribution capabilities from their phones, including uploads, analytics, and payouts.',
    date: '2025-05-13',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/05/13/too-lost-mobile-platform/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/05/too-lost-mobile-app.jpg',
  },
  {
    title: 'Manifest Financial Partners with Too Lost',
    summary: 'New payment partnership brings flexible financial tools and payout options to independent artists and labels.',
    date: '2025-05-05',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/05/05/manifest-financial-too-lost-partnership/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/05/manifest-financial-app.jpg',
  },
  {
    title: 'Too Lost Fan Blast: Keeping Fans Engaged and Up to Date',
    summary: 'New Fan Blast tool allows artists to communicate directly with their audience across streaming platforms.',
    date: '2025-04-03',
    source: 'Musically',
    url: 'https://musically.com/2025/04/03/too-lost-fan-blast-keeping-fans-engaged-and-up-to-date/',
    image: 'https://i0.wp.com/musically.com/wp-content/uploads/2025/04/Screenshot-2025-04-02-at-14.15.25-scaled.jpg?fit=2560%2C1541&ssl=1',
  },
  {
    title: 'Too Lost Partners with Lissen Interactive Platform',
    summary: 'Partnership integrates interactive listening experiences into the Too Lost distribution ecosystem.',
    date: '2025-04-01',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/04/01/too-lost-lissen-partnership-interactive-platform/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/04/toolost-lissen-750-X-500-1024x683.png',
  },
  {
    title: 'Genius Partners with Too Lost on New Distribution Venture',
    summary: 'Collaboration combines Genius editorial platform with Too Lost distribution tech to support emerging artists.',
    date: '2025-03-13',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/03/13/genius-too-lost-partnership/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/03/genius-distro-too-lost-partnership.png',
  },
  {
    title: 'Big Ass Kids Team with Too Lost for Indie Music Distribution',
    summary: 'New partnership brings hip-hop collective into the Too Lost ecosystem for independent distribution.',
    date: '2025-03-04',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2025/03/04/big-ass-kids-team-too-lost-indie-music-distribution/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2025/03/big-ass-mids-music-man-too-lost.jpg',
  },
  {
    title: 'Why Top Artists Are Turning to Distribution Company Too Lost',
    summary: 'Billboard profiles the rapid rise of Too Lost and why established artists are choosing independent distribution over major labels.',
    date: '2025-02-12',
    source: 'Billboard',
    url: 'https://www.billboard.com/pro/too-lost-distribution-greg-hirschhorn-interview/',
    image: 'https://www.billboard.com/wp-content/uploads/2025/02/Gregory-Hirschhorn-cr-Keith-Morse-press-2025-billboard-pro-1260.jpg?w=1024',
  },
  {
    title: 'Too Lost Featured on Forbes 30 Under 30',
    summary: 'Cofounders Gregory Hirschhorn, Bjarki Larusson, and Alex Silverstein named to Forbes 30 Under 30 Music list.',
    date: '2025-01-01',
    source: 'Forbes',
    url: 'https://www.forbes.com/profile/too-lost/',
    image: '/news/forbes-30-under-30.png',
  },
  {
    title: 'Deep Dive Into Data with Too Lost\'s Advanced Analytics',
    summary: 'Musically explores how Too Lost\'s analytics tools give independent artists major-label-level data insights.',
    date: '2024-12-03',
    source: 'Musically',
    url: 'https://musically.com/2024/12/03/deep-dive-into-data-with-too-losts-advanced-analytics/',
    image: 'https://musically.com/wp-content/uploads/2024/12/toolost.jpg',
  },
  {
    title: 'HE.SHE.THEY Records Partners with Too Lost',
    summary: 'Inclusive electronic music label joins Too Lost for global distribution of its diverse roster.',
    date: '2024-09-30',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2024/09/30/he-she-they-records-too-lost-partnership/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2024/09/he-she-they-records-announce-partnership-with-global-music-distribution-platform-too-lost.png',
  },
  {
    title: 'Too Lost Grows Team with New Director of HR and A&R',
    summary: 'Company expands leadership team as it scales operations and artist services.',
    date: '2024-09-18',
    source: 'Digital Music News',
    url: 'https://www.digitalmusicnews.com/2024/09/18/too-lost-growing-new-director-of-hr-ar/',
    image: 'https://www.digitalmusicnews.com/wp-content/uploads/2024/09/too-lost-new-hire.jpg',
  },
  {
    title: 'Too Lost Extends Publishing Admin Deal with BMG',
    summary: 'Extended partnership strengthens Too Lost\'s publishing administration capabilities across thousands of compositions worldwide.',
    date: '2024-02-29',
    source: 'Celebrity Access',
    url: 'https://celebrityaccess.com/2024/02/29/too-lost-extends-publishing-admin-deal-with-bmg/',
    image: 'https://celebrityaccess.com/wp-content/uploads/2024/02/toolostbmg2024.png',
  },
  {
    title: 'AI Music App Hook Expands Distribution with Too Lost Partnership',
    summary: 'AI remix platform integrates Too Lost distribution to deliver user-created remixes to streaming services.',
    date: '2025-08-15',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/ai-music-app-hook-expands-distribution-network-with-too-lost-partnership/',
    image: 'https://www.musicbusinessworldwide.com/files/2023/10/HOOK-Gaurav-Sharma-photo-credit-Florian-Koenigsberger-e1697107704168.jpg',
  },
  {
    title: 'Michael Lewan Named Executive Director of Music Fights Fraud Alliance',
    summary: 'Too Lost joins YouTube Music, ONErpm, Revelator, and others as founding members of the anti-fraud coalition.',
    date: '2025-07-10',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/michael-lewan-named-executive-director-of-music-fights-fraud-alliance-youtube-music-onerpm-revelator-too-lost-and-more-join-as-members/',
    image: 'https://www.musicbusinessworldwide.com/files/2025/02/michael-lewan-hi-res-photo-1-e1740576151628.jpeg',
  },
  {
    title: 'GYRO.Group Recruits Henry Compton',
    summary: 'Australia\'s leading indie distributor strengthens leadership team with key hire.',
    date: '2026-05-13',
    source: 'Billboard',
    url: 'https://www.billboard.com/pro/gyro-group-recruits-henry-compton/',
    image: 'https://www.billboard.com/wp-content/uploads/2026/05/henry-compton-1800-2026.jpg?w=1024',
  },
  {
    title: 'GYRO.Group Expands Into Latin America with New Office in Brazil',
    summary: 'Australia\'s largest independent distribution company opens operations in Brazil to serve growing Latin market.',
    date: '2026-04-15',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/australias-gyro-group-expands-into-latin-america-with-new-office-in-brazil/',
    image: 'https://www.musicbusinessworldwide.com/files/2026/03/Team-Photo-e1774529446743.jpg',
  },
  {
    title: 'GYRO.Group Senior Leadership Promotions',
    summary: 'Henry Compton, Adrian Burke, and Alison Bremner promoted in leadership restructure.',
    date: '2026-05-13',
    source: 'The Music',
    url: 'https://themusic.com.au/industry/gyro-group-senior-leaderships-promotions-henry-compton-adrian-burke-alison-bremner/cr3IZGdmaWg/13-05-26',
    image: 'https://media.themusic.com.au/images/standard/news-25/2506-gy-img-6958-2.990x660.webp',
  },
  {
    title: 'GYRO.Group Appoints Matthew Rogers as Chief Commercial Officer',
    summary: 'Rogers takes on expanded role leading commercial strategy across GYRO.Group and DistroDirect.',
    date: '2025-06-20',
    source: 'Billboard',
    url: 'https://www.billboard.com/pro/gyro-group-appoints-matthew-rogers-chief-commercial-officer/',
    image: 'https://www.billboard.com/wp-content/uploads/2025/06/GY_IMG_6958-2.jpg?w=1024',
  },
  {
    title: 'Power 50: Viv Mellish & Andy Irvine, GYRO.Group',
    summary: 'G.Y.R.O. leadership recognized in Australia\'s annual music industry power list.',
    date: '2025-11-26',
    source: 'The Music',
    url: 'https://themusic.com.au/industry/power-50-2025-viv-mellish-andy-irvine-gyrostream/jpIsgIOChYQ/26-11-25',
    image: 'https://media.themusic.com.au/images/standard/power-50-2025/2025-viv-mellish-andy-irvine.990x660.webp',
  },
  {
    title: 'G.Y.R.O. and DistroDirect Launch Group Speed Artist Services Venture',
    summary: 'New artist services company combines marketing firepower with distribution infrastructure.',
    date: '2025-03-10',
    source: 'Music Business Worldwide',
    url: 'https://www.musicbusinessworldwide.com/australias-gyrostream-and-distrodirect-launch-group-speed-artist-services-venture/',
    image: 'https://www.musicbusinessworldwide.com/files/2024/03/Screenshot-2024-03-06-at-19.06.42-e1709752024364.jpg',
  },
  {
    title: 'How This Aussie Company Helps Indie Musicians Crack the Streaming Code',
    summary: 'The Guardian profiles GYRO.Group\'s innovative approach to supporting independent artists in the streaming era.',
    date: '2025-02-26',
    source: 'The Guardian',
    url: 'https://www.theguardian.com/nab-innovative-businesses/2025/feb/26/how-this-aussie-company-helps-indie-musicians-crack-the-streaming-code',
    image: 'https://i.guim.co.uk/img/media/f76827146eac050da28870ea1641e96645fdb09c/0_0_6637_3982/master/6637.jpg?width=700&quality=85&auto=format&fit=max&s=e5d13ff102b045621a5ee2e69a9a5f72',
  },
  {
    title: 'G.Y.R.O. Expands Offerings with GYROPublishing Admin Service',
    summary: 'New publishing administration service extends G.Y.R.O.\'s capabilities for Australian independent artists.',
    date: '2023-09-01',
    source: 'The Music',
    url: 'https://themusic.com.au/industry/gyrostream-expands-offerings-with-gyropublishing-admin-service/QHn-UlVUV1Y/01-09-23',
    image: 'https://media.themusic.com.au/images/standard/news-23/gyrostream-27-1.990x660.webp',
  },
  {
    title: 'Billboard Indie Power Players 2026',
    summary: 'Too Lost leadership featured among Billboard\'s annual Indie Power Players photo gallery.',
    date: '2026-06-01',
    source: 'Billboard',
    url: 'https://www.billboard.com/photos/indie-power-players-2026-photos-1236269720/',
    image: 'https://www.billboard.com/wp-content/uploads/2026/06/02-raye-indie-power-players-2026-billboard-1800.jpg?w=1024',
  },
  {
    title: 'Indie Music Execs on AI, Consolidation, and Industry Changes',
    summary: 'Industry leaders including Too Lost weigh in on the biggest forces reshaping independent music.',
    date: '2026-06-01',
    source: 'Billboard',
    url: 'https://www.billboard.com/lists/indie-music-execs-ai-consolidation-changes-affect/emmanuel-zunz-onerpm-2',
    image: 'https://www.billboard.com/wp-content/uploads/2026/05/indie-power-players-intro-2026-bb5-billboard-1800.jpg?w=1024',
  },
  {
    title: 'What Excites Music Execs Most About the Indie World',
    summary: 'Top executives share what drives their enthusiasm for the independent music sector.',
    date: '2026-06-01',
    source: 'Billboard',
    url: 'https://www.billboard.com/lists/what-excites-music-execs-most-about-the-indie-world/shawn-holiday-giant-music-3',
    image: 'https://www.billboard.com/wp-content/uploads/2026/05/indie-power-players-intro-2026-bb5-billboard-1800.jpg?w=1024',
  },
  {
    title: 'Indie Music Execs on Biggest Industry Changes',
    summary: 'Billboard roundtable on the transformative shifts in independent music distribution and services.',
    date: '2026-06-01',
    source: 'Billboard',
    url: 'https://www.billboard.com/lists/indie-music-execs-biggest-industry-changes/',
    image: 'https://www.billboard.com/wp-content/uploads/2026/05/indie-power-players-intro-2026-bb5-billboard-1800.jpg?w=1024',
  },
  {
    title: 'Billboard Music Industry 40 Under 40',
    summary: 'Too Lost founders recognized on Billboard\'s prestigious 40 Under 40 list for music industry leaders.',
    date: '2025-11-01',
    source: 'Billboard',
    url: 'https://www.billboard.com/p/music-industry-40-under-40-list-2025/',
    image: 'https://www.billboard.com/wp-content/uploads/2025/05/Billboard-40-Under-40-2025-featured.jpg?w=1024',
  },
  {
    title: 'G.Y.R.O. on Spotify\'s Direct Artist Upload Strategy',
    summary: 'Independent artists need extra support services beyond basic upload capabilities, G.Y.R.O. argues.',
    date: '2024-06-15',
    source: 'The Music Network',
    url: 'https://themusicnetwork.com/news/exclusive-aussie-distributor-gyrostream-on-spotifys-direct-artist-upload-strategy-independent-artists-need-extra-support-services',
    image: 'https://images-r2-1.thebrag.com/tmn/uploads/BigSound-45.jpg',
  },
]
